# Generated by Django 5.1.3 on 2024-11-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsiler',
            name='document',
        ),
    ]
